# Generated by Django 5.0.2 on 2024-02-28 20:31

import app.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('avatar', models.ImageField(default='cobalt1.webp', upload_to=app.utils.avatar_path)),
                ('like_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='cobalt1.webp', upload_to=app.utils.image_path)),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('bid', models.FloatField()),
                ('owner', models.CharField(max_length=28)),
                ('owner_username', models.CharField(max_length=28)),
                ('ends_in', models.TimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.author')),
            ],
        ),
    ]
